services:
  api:
    build: .
    ports:
      - "5553:5553"
    environment:
      - WORKER=${WORKER}
      - VERSION=${VERSION}
      - MICROSERVICE_SECRET_KEY=${MICROSERVICE_SECRET_KEY}
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - PASSWORD=${PASSWORD}
      - HOST=${HOST}
      - PORT=${PORT}
    restart: unless-stopped
