services:
  api:
    build: .  # Собираем образ из текущей директории
    volumes:
      - .:/app
      - ./credentials.json:/app/credentials.json
    ports:
      - "5551:5551"  # Прокидываем порт 8000 на хост-машину
    environment:
      - APP_MANAGER=${APP_MANAGER}
      - VERSION=${VERSION}
      - MICROSERVICE_SECRET_KEY=${MICROSERVICE_SECRET_KEY}
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - PASSWORD=${PASSWORD}
      - HOST=${HOST}
      - PORT=${PORT}
      - ENVIRONMENT=${ENVIRONMENT}
      - DEFAULT_WB_TECH_TABLE_ID=${DEFAULT_WB_TECH_TABLE_ID}
    restart: unless-stopped  # Перезапускать сервис при сбоях
